### ISSUE TITLE
Norton flagging several files from libGDX as malicious and removing the files

### ISSUE THREAD

**Issue by cdelstad** [boniatillo-com/PhaserEditor#11]
Norton is flagging several files from libGDX with WS.Reputation.1, such as gdx64.dll, and removing them from the zip file.

Note from Norton:
File Actions
File: c:\users\chad\desktop\phaser-editor-1.3.0.ga.jre.win64\phaser editor\plugins\phasereditor.libgdx.win32_1.3.0.20161130\ gdx64.dll Removed

Here is a note on libGDX' GitHub:
https://github.com/libgdx/libgdx/issues/2046

**Comment by boniatillo-com** [comment]
Thanks @cdelstad for reporting this issue. Reading the LibGDX developer comment, we can say it is not a real threat. However, we use LibGDX specially for Audio playback and texture packing, so in future releases we could find a better way to playback audio and keep only with the texture packing algortithm, it means, we could remove all DLL dependencies from LibGDX.

**Comment by samsstuff** [comment]
I don't have the dll's because of linux but I get no threats in linux for anything libgdx wise, been using libgdx for years, it's probably just nortons throwing a false positive as stated in that thread you can contact nortons to report false positives.
Libgdx has no control over what a antivirus throws out as a threat

> Here's where you can report false positives: https://submit.symantec.com/false_positive/

**Comment by boniatillo-com** [comment]
No more activity in this issue... I am closing it.
