### ISSUE TITLE
Enhancements for SceneEditor

### ISSUE THREAD

**Issue by ponderboy** [boniatillo-com/PhaserEditor#14]
I don't know exactly where to leave my considerations. 

I'm happy I found Phaser Editor, because it'll help me creating scenes more intuitive than it would have been with just code. Mighty Editor is not continued and Tiled is still not able to work with just pictures or at least Phaser does not integrate with it. 

Anyway, while now using it I found a few things more then necessary. My Canvas Scene broke totally when changing an atlas file outside. It seems the whole atlas update progress and changing files after already adding them to a scene is still very beta. 
I would love to be able to change sprites later on. Select a sprite and be able to change its texture or image via the right mouse button menu for example or by just selecting a different one in the asset window. This way, if something went wrong or a file is missing or a texture was deleted in an atlas file, you could just exchange it, while keeping all it's properties. By now I have to manually delete the sprite drag a new one on the canvas and lay it out etc.

Another thing very much appreciated, would be to move elements by arrow keys. Similar to Photoshop or others, it would be great to move them by pixels and Shift+Arrow for ten pixel steps. 

It'd be very helpful to be able to just duplicate sprites. And have them appear within the same group. At the moment I copy paste. But then I have to manually drag the sprite into the group. Or maybe Shift+V for pasting in the same group or something. 

Not being able to lock layers or sprites is also a bit frustrating. 

It'd be awesome if there would also be a field to change the alpha of sprites. (I need to create transparent boundaries for physics.)

Selecting more then one sprite and being able to scale and rotate them would be very helpful as well.

That's a lot of things I know and I'm not expecting to have everything within the next update. But I'm sure it would gracefully improve the overall usability of the scene editor.

**Comment by ponderboy** [comment]
Alright, I apologize! I just realized via right mouse button menu > pick > Deny pick object or just Shift+P.

**Comment by boniatillo-com** [comment]
Hi @ponderboy 

This is the right place for your very welcome considerations, actually, lot of them are going to be included in the next version. Just take a look to the commits of the past weeks and you will see a lot about refactoring tools.

Let me answer your points one by one:

> My Canvas Scene broke totally when changing an atlas file outside. It seems the whole atlas update progress and changing files after already adding them to a scene is still very beta. I would love to be able to change sprites later on. Select a sprite and be able to change its texture or image...

Yes, it is very basic, and the better option you have right now is to find/replace yourself in the canvas JSON file the assets references. It is a bit of hack but if you look it is a friendly json with an "asset-table" that you can change very well. I mention this as a temporary solution because in the next release you will get a new "Swap Texture" function that allow you to change the texture of a sprite (right now you can change only the frame). Also you will be able to swap a texture globally, this means, that you click on a key in the Assets explorer and ask to replace it by other key in all the canvas of the project. We just want to make very easy to replace your demo assets for the real assets.

In addition we created the Prefab concept. It is a canvas file that you can use in other canvas files. It means, you will be able to create visually custom Phaser.Sprite and Phaser.Group. So if you use prefab instances in your scenes, then it is all about to change the prefab's texture, then all the scenes gets the update.

> Another thing very much appreciated, would be to move elements by arrow keys. Similar to Photoshop or others, it would be great to move them by pixels and Shift+Arrow for ten pixel steps.

Created an issue for this: #18

> It'd be very helpful to be able to just duplicate sprites. And have them appear within the same group. At the moment I copy paste...

Created an issue for this: #15

> Not being able to lock layers or sprites is also a bit frustrating.

Yes, if what you mean is to keep an object untouchable "Deny pick" is the option. 

> It'd be awesome if there would also be a field to change the alpha of sprites. (I need to create transparent boundaries for physics.)

Created issue for this: #16

> Selecting more then one sprite and being able to scale and rotate them would be very helpful as well.

Created issue for this: #17

> That's a lot of things I know and I'm not expecting to have everything within the next update. But I'm sure it would gracefully improve the overall usability of the scene editor.

I think lot of them could be implemented for the next release. I really appreciate your thoughts, many of them are in our private TODO list so we are going to give priority to them. 

I encourage you to keep sharing your ideas with us, this is the best place to do it, so others can participate in/follow the thread.

Thanks
Arian

**Comment by boniatillo-com** [comment]
You can follow the progress in the plan of your issues here:

https://github.com/boniatillo-com/PhaserEditor/projects/1?fullscreen=true

**Comment by boniatillo-com** [comment]
I close this, this issue was splitted in others. In relation to the change of the textures it is done too, we added refactoring tool to rename/move/delete things and to change textures is possible in a canvas file or in the whole project.
