### ISSUE TITLE
field for name (in addition to variable name)

### ISSUE THREAD

**Issue by ponderboy** [boniatillo-com/PhaserEditor#19]
In the scene editor you can assign names to groups and sprites. But these are the variable names. If I loop through a group and want to check against a specific element and other cases, it would be helpful to have an assigned name. 

So I'd find either an additional field helpful or the (var) name field would also act as a field for the (string) name. 

And thanks for your reply to my other suggestions. It's great to see that you're already planing on implementing lots in the next release.

**Comment by boniatillo-com** [comment]
I can add the `name` field. However, it would be great if you explain a bit more about the cases you need it. Maybe is there a plugin that uses it? I mean, the question is that to access to an object you can make it public, or to add extra info to an object you can use the `data` field.

We have in our TODO list a task about to implement a sort of tags or lists. A mechanism to "group" objects but without the use of Phaser groups, because Phaser groups have many other functions.

**Comment by ponderboy** [comment]
My example is the following: 
I have a fish that shall not hit obstacles (that are physicGroups inside a group). I would like to be able to log what obstacle was hit. (onCollide > log > obstacle.name ) So it would be nice if I could give sprites and groups a name or if they would get the default var name assigned. 

Or if you loop through a group and want to apply the same positions but to the "rabbit" a very specific position. ( forEach > if ( item.name == "rabbit" ) > item.x = 15 )

Hope that explains why I thought it'd be useful. Also it was first confusing. Maybe "var name" would be better for the field?!

**Comment by boniatillo-com** [comment]
>  Maybe "var name" would be better for the field?!

Yes it is true is confusing, I am going to rename it.

>  I would like to be able to log what obstacle was hit.

True, logging...!

Thanks

**Comment by boniatillo-com** [comment]
Ah, in the meantime you can use the `data` field. Just use as data something like:

```
{
  "name" : "rabbit"
}
```

and in code `( forEach > if ( item.name == "rabbit" ) > item.x = 15 )`.

**Comment by boniatillo-com** [comment]
Done. The old field was renamed to `varName` and we introduced the new `name` field.

Is better to separate both names because they are not the same. The Phaser object name is a string and any value is valid, but for the `varName` only JS identifiers are valid.


![image](https://cloud.githubusercontent.com/assets/12187299/23220439/01848f50-f8f0-11e6-964e-96008101a001.png)
