### ISSUE TITLE
Next version release date.

### ISSUE THREAD

**Issue by aliklev** [boniatillo-com/PhaserEditor#23]
Hi.When is the release date of new  version  or beta?

**Comment by boniatillo-com** [comment]
Less than a month I think. If the Mac hardware arrive then maybe a week more, if possible we want to deliver the next release with the so waited Mac version.

**Comment by boniatillo-com** [comment]
Do you have any interest in particular?

**Comment by aliklev** [comment]
We are interesting and want  to try next release for Windows and typescript support.

**Comment by boniatillo-com** [comment]
We hope for the date the Typescript.java project will release its 1.2.0 version, to include it in the editor.

https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0

**Comment by aliklev** [comment]
Hi.
Can you supply beta or rc  version for windows release?
or how can we compile the source for windows?
We decided to check the canvas typescript compilation feature, may be in early stage ..
thank you.

**Comment by boniatillo-com** [comment]
Hi, other users requested the build guide (#12 ) but yet we do not decide put some time on create builds scripts or write a detailed manual-build guide.

I think it will be more easy to send you a private snapshot of the current development, it will be great if you give us some feedback, I just need two or three days to prepare the update site and a small guide about the new features because Canvas is now splitted in State, Group and Sprite.

**Comment by boniatillo-com** [comment]
While I build the update site for preview you can look inside the code generated in this game I am using to confirm the typescript code is working.

It is the WebContent folder of the project, it has a `tsconfig.json` file so you can open it in Visual Studio Code and try it.

[TypeScriptDemo_WebContent.zip](https://github.com/boniatillo-com/PhaserEditor/files/805069/TypeScriptDemo_WebContent.zip)

**Comment by boniatillo-com** [comment]
Hi @aliklev 

You can download a snapshot of the current development here:

https://dl.dropboxusercontent.com/u/100685682/Phaser%20Editor/1.3.1_snapshot_dev/Phaser-Editor-1.3.1.snapshot_dev.jre.win64.zip

Note now to create a scenes you have 3 options:

1- Create a sprite
2- Create a group
3- Create a state

In the creation dialog select as language typescript.

Look now in the Assets view you will see all the scenes, so you can drag/drop sprites and groups inside the scenes.

Please remember this is on active development, if you find an issue comment it here, don't create a new issue.

**Comment by aliklev** [comment]
Thank you very much, we will test it soon.

**Comment by aliklev** [comment]
Hi.
First question:
How to add prefab to another scene?

**Comment by aliklev** [comment]
The option Add Prefab to State like "Add Sprite" would be very helpful and not only "copy paste" from another state.

**Comment by boniatillo-com** [comment]
To add a prefab to the state you drag it from the Assets view and drop it to the scene. No need to copy/paste.

To add it via the Add Sprite dialog is good option too, we are going to include it.

By the way, is the TypeScript generation working well?

**Comment by aliklev** [comment]
We are testing, I think will be nice to add  clear typescript templates projects to version.
Thank you.

**Comment by boniatillo-com** [comment]
Yes, we are going to introduce a new project wizard, to customize the initial project content. So we keep the old project wizard as a **New Phaser Project From Example** and the new wizard as **New Phaser Project**. In the new wizard you will be able to customize certain parameters and one of them is the language, JavaScript or TypeScript. In a future we can also give some TypeScript examples project too.

**Comment by tomb-pss** [comment]
Hopefully, this is the right place to put this feedback. I've been playing with the dev snapshot and have run into a couple of big issues with the typescript generation for prefabs:

The first one is that the constructor for generated group prefabs don't specify any parameters as optional (using '?'). This isn't a big deal except that when one of these prefabs is placed in another, the code that calls that constructor only provides the first 2 parameters (aGame and aParent). This won't compile with TypeScript.

The second issue is a weird one. If a prefab has objects marked as public, so that they are assigned to properties, and then that prefab is placed inside of another, the generated code for the outer prefab attempts to create properties for the inner prefabs' objects. This happens in both TypeScript and JavaScript, but produces compile errors in TypeScript.

Anyways, just figured I'd call these out ahead of the release of the new version, in case they weren't already known.

**Comment by boniatillo-com** [comment]
Hi @tomb-pss 

Yes, a couple of issues are fixed in my local copy, however I will check again. I am thinking on do a candidate release with all features implemented and all our tests passed. This release comes with a lot of stuff and it will be great if some users can test it while we write the documentation of the new features.

Thanks.

**Comment by tomb-pss** [comment]
@boniatillo-com Sounds good - if you put out an RC, I'll definitely test it out :)

**Comment by boniatillo-com** [comment]
Strange, I uninstalled it and reinstalled but the version keep the same. Now I just did an update and the project wizard works. Thanks!

**Comment by boniatillo-com** [comment]
(deleted a comment that I posted by mistake)
