### ISSUE TITLE
If Phaser.Group is public, the code is exported as 'Phaser.Sprite'

### ISSUE THREAD

**Issue by mulovad** [boniatillo-com/PhaserEditor#33]
If Phaser.Group is public, the variable type is exported as 'Phaser.Sprite' in Phaser Editor 1.4.0_preview.

**Comment by boniatillo-com** [comment]
Hi @mulovad 

I guess you are talking about the TypeScript code generator.

That error was fixed in an update, please update the editor to 1.4.0_preview.2.

Just go to Help > Check for Updates.

If you have any issue updating the product please contact with us. If you are behind a proxy you may configure it on Windows > Preferences > Network Connections.

**Comment by boniatillo-com** [comment]
Duplication of #29
