### ISSUE TITLE
AddChild to sprite prefab

### ISSUE THREAD

**Issue by nicloay** [boniatillo-com/PhaserEditor#35]
Is this possible to add another sprite to the sprite prefab using this method? http://phaser.io/docs/2.6.2/Phaser.Sprite.html#addChild

With context menu->add->sprite new sprite just replace existing one.

Thanks.

**Comment by boniatillo-com** [comment]
Honestly, just I just realize that it is possible on Phaser :(

For me to have children is a behavior of Groups, not Sprites. But it is true, I just did some examples and it works. Phaser objects extend the PIXI DisplayObject that is a container and can have children.

However I am happy that you mention it because the main difference between a Group or Sprite as container is that when you apply physics to the parent sprite the children get updated, but in case of the Group you have to enable a body in all the children.

I will try to deliver this as an update of the current preview version, to include it then in the final 1.4.0.GA.

**Comment by boniatillo-com** [comment]
I opened a thread in the Phaser 3 google group related to this issue:

https://groups.google.com/forum/#!topic/phaser3-dev/jNb_9i0_EpE

I think in dependence of what is going to be implemented in Phaser 3 we are going to provide support to this feature.

**Comment by boniatillo-com** [comment]
I close this. In Phaser v2 it is possible to add a child to a sprite but in Phaser v3 it is not going to be possible: https://groups.google.com/forum/#!topic/phaser3-dev/jNb_9i0_EpE
